/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as StoriesImport } from './routes/stories'
import { Route as AdminpageImport } from './routes/adminpage'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const StoriesRoute = StoriesImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRoute,
} as any)

const AdminpageRoute = AdminpageImport.update({
  id: '/adminpage',
  path: '/adminpage',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/adminpage': {
      id: '/adminpage'
      path: '/adminpage'
      fullPath: '/adminpage'
      preLoaderRoute: typeof AdminpageImport
      parentRoute: typeof rootRoute
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adminpage': typeof AdminpageRoute
  '/stories': typeof StoriesRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adminpage': typeof AdminpageRoute
  '/stories': typeof StoriesRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/adminpage': typeof AdminpageRoute
  '/stories': typeof StoriesRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/adminpage' | '/stories'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/adminpage' | '/stories'
  id: '__root__' | '/' | '/adminpage' | '/stories'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminpageRoute: typeof AdminpageRoute
  StoriesRoute: typeof StoriesRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminpageRoute: AdminpageRoute,
  StoriesRoute: StoriesRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/adminpage",
        "/stories"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/adminpage": {
      "filePath": "adminpage.jsx"
    },
    "/stories": {
      "filePath": "stories.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
